name: Run tests

on: [push, pull_request]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependecies & Test
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: npm
      - run: |
          npm install
          npm run lint
          npm test
